// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/example/clean-architecture/entity"
	mock "github.com/stretchr/testify/mock"
)

// AddressRepositoryMock is an autogenerated mock type for the IRepository type
type AddressRepositoryMock struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *AddressRepositoryMock) Create(_a0 *entity.Address) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Address) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *AddressRepositoryMock) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *AddressRepositoryMock) GetAll() ([]*entity.Address, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*entity.Address
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entity.Address, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entity.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Address)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *AddressRepositoryMock) GetByID(id int) (*entity.Address, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*entity.Address, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *entity.Address); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: userID
func (_m *AddressRepositoryMock) GetByUserID(userID int) ([]*entity.Address, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*entity.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*entity.Address, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) []*entity.Address); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *AddressRepositoryMock) Update(_a0 *entity.Address) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Address) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAddressRepositoryMock creates a new instance of AddressRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddressRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddressRepositoryMock {
	mock := &AddressRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
