// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/example/clean-architecture/entity"
	mock "github.com/stretchr/testify/mock"
)

// AddressServiceMock is an autogenerated mock type for the IService type
type AddressServiceMock struct {
	mock.Mock
}

// CreateAddress provides a mock function with given fields: _a0
func (_m *AddressServiceMock) CreateAddress(_a0 *entity.Address) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateAddress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Address) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAddress provides a mock function with given fields: id
func (_m *AddressServiceMock) DeleteAddress(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAddress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAddress provides a mock function with given fields: id
func (_m *AddressServiceMock) GetAddress(id int) (*entity.Address, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetAddress")
	}

	var r0 *entity.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*entity.Address, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *entity.Address); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAddressesByUser provides a mock function with given fields: userID
func (_m *AddressServiceMock) GetAddressesByUser(userID int) ([]*entity.Address, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAddressesByUser")
	}

	var r0 []*entity.Address
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*entity.Address, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) []*entity.Address); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Address)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAddresses provides a mock function with no fields
func (_m *AddressServiceMock) ListAddresses() ([]*entity.Address, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListAddresses")
	}

	var r0 []*entity.Address
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entity.Address, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entity.Address); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Address)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAddress provides a mock function with given fields: _a0
func (_m *AddressServiceMock) UpdateAddress(_a0 *entity.Address) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAddress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Address) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAddressServiceMock creates a new instance of AddressServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddressServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddressServiceMock {
	mock := &AddressServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
